-- CONSTRUCTORA WM/M&S - CONSTRUYENDO EL FUTURO
-- Fix sync_status CHECK in remote DB

ALTER TABLE projects DROP CONSTRAINT projects_sync_status_check, ADD CONSTRAINT projects_sync_status_check CHECK (sync_status = ANY (ARRAY[''pending''::text, ''syncing''::text, ''synced''::text, ''error''::text, ''created_offline''::text, ''updated_offline''::text, ''sync_failed''::text]));
ALTER TABLE budgets DROP CONSTRAINT budgets_sync_status_check, ADD CONSTRAINT budgets_sync_status_check CHECK (sync_status = ANY (ARRAY[''pending''::text, ''syncing''::text, ''synced''::text, ''error''::text, ''created_offline''::text, ''updated_offline''::text, ''sync_failed''::text]));
ALTER TABLE budget_items DROP CONSTRAINT budget_items_sync_status_check, ADD CONSTRAINT budget_items_sync_status_check CHECK (sync_status = ANY (ARRAY[''pending''::text, ''syncing''::text, ''synced''::text, ''error''::text, ''created_offline''::text, ''updated_offline''::text, ''sync_failed''::text]));
ALTER TABLE budget_item_breakdowns DROP CONSTRAINT budget_item_breakdowns_sync_status_check, ADD CONSTRAINT budget_item_breakdowns_sync_status_check CHECK (sync_status = ANY (ARRAY[''pending''::text, ''syncing''::text, ''synced''::text, ''error''::text, ''created_offline''::text, ''updated_offline''::text, ''sync_failed''::text]));
ALTER TABLE financial_transactions DROP CONSTRAINT financial_transactions_sync_status_check, ADD CONSTRAINT financial_transactions_sync_status_check CHECK (sync_status = ANY (ARRAY[''pending''::text, ''syncing''::text, ''synced''::text, ''error''::text, ''created_offline''::text, ''updated_offline''::text, ''sync_failed''::text]));
ALTER TABLE payroll_employees DROP CONSTRAINT payroll_employees_sync_status_check, ADD CONSTRAINT payroll_employees_sync_status_check CHECK (sync_status = ANY (ARRAY[''pending''::text, ''syncing''::text, ''synced''::text, ''error''::text, ''created_offline''::text, ''updated_offline''::text, ''sync_failed''::text]));
ALTER TABLE warehouse_stock DROP CONSTRAINT warehouse_stock_sync_status_check, ADD CONSTRAINT warehouse_stock_sync_status_check CHECK (sync_status = ANY (ARRAY[''pending''::text, ''syncing''::text, ''synced''::text, ''error''::text, ''created_offline''::text, ''updated_offline''::text, ''sync_failed''::text]));
ALTER TABLE profiles DROP CONSTRAINT profiles_sync_status_check, ADD CONSTRAINT profiles_sync_status_check CHECK (sync_status = ANY (ARRAY[''pending''::text, ''syncing''::text, ''synced''::text, ''error''::text, ''created_offline''::text, ''updated_offline''::text, ''sync_failed''::text]));
ALTER TABLE apu_library DROP CONSTRAINT apu_library_sync_status_check, ADD CONSTRAINT apu_library_sync_status_check CHECK (sync_status = ANY (ARRAY[''pending''::text, ''syncing''::text, ''synced''::text, ''error''::text, ''created_offline''::text, ''updated_offline''::text, ''sync_failed''::text]));
ALTER TABLE clients DROP CONSTRAINT clients_sync_status_check, ADD CONSTRAINT clients_sync_status_check CHECK (sync_status = ANY (ARRAY[''pending''::text, ''syncing''::text, ''synced''::text, ''error''::text, ''created_offline''::text, ''updated_offline''::text, ''sync_failed''::text]));
ALTER TABLE project_logs DROP CONSTRAINT project_logs_sync_status_check, ADD CONSTRAINT project_logs_sync_status_check CHECK (sync_status = ANY (ARRAY[''pending''::text, ''syncing''::text, ''synced''::text, ''error''::text, ''created_offline''::text, ''updated_offline''::text, ''sync_failed''::text]));
ALTER TABLE suppliers DROP CONSTRAINT suppliers_sync_status_check, ADD CONSTRAINT suppliers_sync_status_check CHECK (sync_status = ANY (ARRAY[''pending''::text, ''syncing''::text, ''synced''::text, ''error''::text, ''created_offline''::text, ''updated_offline''::text, ''sync_failed''::text]));
ALTER TABLE purchase_orders DROP CONSTRAINT purchase_orders_sync_status_check, ADD CONSTRAINT purchase_orders_sync_status_check CHECK (sync_status = ANY (ARRAY[''pending''::text, ''syncing''::text, ''synced''::text, ''error''::text, ''created_offline''::text, ''updated_offline''::text, ''sync_failed''::text]));
ALTER TABLE purchase_order_items DROP CONSTRAINT purchase_order_items_sync_status_check, ADD CONSTRAINT purchase_order_items_sync_status_check CHECK (sync_status = ANY (ARRAY[''pending''::text, ''syncing''::text, ''synced''::text, ''error''::text, ''created_offline''::text, ''updated_offline''::text, ''sync_failed''::text]));
ALTER TABLE payroll_records DROP CONSTRAINT payroll_records_sync_status_check, ADD CONSTRAINT payroll_records_sync_status_check CHECK (sync_status = ANY (ARRAY[''pending''::text, ''syncing''::text, ''synced''::text, ''error''::text, ''created_offline''::text, ''updated_offline''::text, ''sync_failed''::text]));
